### ISSUE TITLE
[BUG] cannot connect to  Sky Wifi Hub SR203

### ISSUE THREAD

**Issue by npercacciante** [RogerSelwyn/Home_Assistant_SkyQ_Hub#5]
I desire to integrate my sky wifi hub mod. SR203 into HA and i  tried to use your Home_Assistant_SkyQ_Hub.
I expect to use it for device_tracker
The model that i have is  Sky Wifi Hub - Moddel SR203

This is the output of homeassistant.log
ERROR (MainThread) [pyskyqhub.skyq_hub] Error parsing data at startup for 192.168.0.1, is this a Sky Router?

**Comment by RogerSelwyn** [comment]
Sorry, the supported model is ER115
